version: '2'
services:
    jhipstersamplegateway-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/JHipsterSampleGateway/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=JHipsterSampleGateway
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
